[XNIO-422] Add information about remote connection address to the Exc…
xnio/xnio pull request #306
Opened 2023-08-16 14:14 UTC by spyrkob

…eption when connection fails

JIRA: https://issues.redhat.com/browse/JBEAP-25233
Upstream: #305

2023-08-24 15:53 UTC, dmlloyd requested changes

2023-08-24 15:53 UTC, dmlloyd commented on nio-impl/src/main/java/org/xnio/nio/Log.java
> +    IOException connectionRefused(String originalMsg, String address, @Cause Throwable cause);
I think we've had previous privacy concerns about logging IP addresses, and I believe this would run afoul of that.

2023-09-07 11:54 UTC, dmlloyd commented on nio-impl/src/main/java/org/xnio/nio/WorkerThread.java
> +                        this.connection.getPeerAddress().toString());
I'd skip the `toString` part: by explicitly calling that method, you are paying the cost of stringifying the address even when trace logging is turned off.

2023-09-07 12:16 UTC, dmlloyd reviewed
You might want to do the same sort of error checking here: https://github.com/xnio/xnio/pull/306/files#diff-e785722e551ce5c5790c76e5af488d8784f76ebaab92a5819ae7cad0cdf641c0R296

Also, make sure that we know that the peer address is in fact valid here - if connection has failed, it might not be (NIO is a bit funny that way).

2023-09-15 10:39 UTC, spyrkob commented
@dmlloyd stupid question - when you say "that the peer address is in fact valid"  - in what way would it be invalid? Looking at connection.getPeerAddress() the address could be `InetAddress.anyLocalAddress()` if the socket was not connected - do you mean to check for that?

2023-09-18 15:42 UTC, dmlloyd commented
> @dmlloyd stupid question - when you say "that the peer address is in fact valid" - in what way would it be invalid? Looking at connection.getPeerAddress() the address could be `InetAddress.anyLocalAddress()` if the socket was not connected - do you mean to check for that?

Right, the socket could be unconnected, at least in principle. I don't remember if XNIO hides that fact from the API consumer though.

2023-10-05 16:07 UTC, spyrkob commented
Thanks @dmlloyd, sorry for delay I was away for a while.

I added a check to see if the SocketChannel is connected and added to log to `openTcpStreamConnection` error handler. 

btw. did you see [Brad's comment](https://github.com/xnio/xnio/pull/305#issuecomment-1711887221) on the upstream issue? Do you know if there are any guidelines what information should be available in the server log?

2023-10-09 12:54 UTC, dmlloyd approved these changes

2023-10-10 05:21 UTC, merged